<?php

namespace App\Http\Controllers\Api;

class ProductController extends ApiController
{

    public function getSearch()
    {
        $json = array(
            'status'    => 0,
            'num_found' => 150,
            'rows'      => 24,
            'items'     => array(
                array(
                    'product_id'                     => 1120,
                    'product_name'                   => '生クリーム デコレーション　5号',
                    'product_price'                  => 2370,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 2360,
                    'product_name'                   => '生クリーム デコレーション　6号',
                    'product_price'                  => 3240,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 3588,
                    'product_name'                   => '生クリーム デコレーション　7号',
                    'product_price'                  => 4320,
                    'product_size'                   => '5',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 4807,
                    'product_name'                   => '生クリーム デコレーション　8号',
                    'product_price'                  => 5400,
                    'product_size'                   => '6',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 5992,
                    'product_name'                   => '生チョココーティングデコレーション　5号',
                    'product_price'                  => 2370,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】生チョコをたっぷりと使用したデコレーションケーキ。お子様から大人まで幅広く人気の商品です。ご希望のメッセージをお入れいたします。
        ※画像は6号サイズのもの',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 7158,
                    'product_name'                   => '生チョココーティングデコレーション　6号',
                    'product_price'                  => 3240,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】生チョコをたっぷりと使用したデコレーションケーキ。お子様から大人まで幅広く人気の商品です。ご希望のメッセージをお入れいたします。
        ※画像は6号サイズのもの',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 8280,
                    'product_name'                   => '生チョココーティングデコレーション　7号',
                    'product_price'                  => 4320,
                    'product_size'                   => '5',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】生チョコをたっぷりと使用したデコレーションケーキ。お子様から大人まで幅広く人気の商品です。ご希望のメッセージをお入れいたします。
        ※画像は6号サイズのもの',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 9354,
                    'product_name'                   => '生チョココーティングデコレーション　8号',
                    'product_price'                  => 5400,
                    'product_size'                   => '6',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】生チョコをたっぷりと使用したデコレーションケーキ。お子様から大人まで幅広く人気の商品です。ご希望のメッセージをお入れいたします。
        ※画像は6号サイズのもの',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 10,
                    'product_comment_evaluate_total' => 2.5,
                    'shop_id'                        => 42647,
                    'facility_name'                  => '和洋菓子 好月堂',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '世田谷区',
                    'district'                       => '八幡山3-35-24',
                    'building_name'                  => '1F',
                    'addr_latitude'                  => '35.669068',
                    'addr_longitude'                 => '139.615774',
                    'display_tel_no'                 => '03-3303-5316',
                    'station1'                       => '八幡山駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 14550,
                    'product_name'                   => '生デコレーションケーキ　5号',
                    'product_price'                  => 3000,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => 'コクのある青梅の産みたて卵を使用して焼き上げたスポンジ生地と、こだわりの熊本県産の生クリームをたっぷりしぼり、国産の苺をふんだんにサンド、トッピングしたデコレーションケーキです。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1.jpg',
                    'product_image2'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1_1.jpg',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42855,
                    'facility_name'                  => 'ラトリエ　アンソレイエ',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10157017000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '東大和市',
                    'district'                       => '上北台2-892-4-105',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.743611',
                    'addr_longitude'                 => '139.410617',
                    'display_tel_no'                 => '042-516-8898',
                    'station1'                       => '上北台駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '8',
                ),
                array(
                    'product_id'                     => 14551,
                    'product_name'                   => '生デコレーションケーキ　6号',
                    'product_price'                  => 3900,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => 'コクのある青梅の産みたて卵を使用して焼き上げたスポンジ生地と、こだわりの熊本県産の生クリームをたっぷりしぼり、国産の苺をふんだんにサンド、トッピングしたデコレーションケーキです。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1.jpg',
                    'product_image2'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1_1.jpg',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42855,
                    'facility_name'                  => 'ラトリエ　アンソレイエ',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10157017000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '東大和市',
                    'district'                       => '上北台2-892-4-105',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.743611',
                    'addr_longitude'                 => '139.410617',
                    'display_tel_no'                 => '042-516-8898',
                    'station1'                       => '上北台駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '8',
                ),
                array(
                    'product_id'                     => 14552,
                    'product_name'                   => '生デコレーションケーキ　7号',
                    'product_price'                  => 5200,
                    'product_size'                   => '5',
                    'reservation_flg'                => '1',
                    'product_description1'           => 'コクのある青梅の産みたて卵を使用して焼き上げたスポンジ生地と、こだわりの熊本県産の生クリームをたっぷりしぼり、国産の苺をふんだんにサンド、トッピングしたデコレーションケーキです。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1.jpg',
                    'product_image2'                 => 'http://s7790605.xaas.jp/images/material/F10157017000001_BD1_1.jpg',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42855,
                    'facility_name'                  => 'ラトリエ　アンソレイエ',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10157017000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '東大和市',
                    'district'                       => '上北台2-892-4-105',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.743611',
                    'addr_longitude'                 => '139.410617',
                    'display_tel_no'                 => '042-516-8898',
                    'station1'                       => '上北台駅',
                    'exit_station1'                  => '',
                    'means1'                         => ' 徒歩',
                    'time_required1'                 => '8',
                ),
                array(
                    'product_id'                     => 11062,
                    'product_name'                   => 'フルーツデコレーション　4号',
                    'product_price'                  => 2808,
                    'product_size'                   => '2',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】季節に合わせて旬のフルーツをふんだんに使っています。※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 11404,
                    'product_name'                   => 'フルーツデコレーション　5号',
                    'product_price'                  => 3456,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】季節に合わせて旬のフルーツをふんだんに使っています。※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 11666,
                    'product_name'                   => 'フルーツデコレーション　6号',
                    'product_price'                  => 4320,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】季節に合わせて旬のフルーツをふんだんに使っています。※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD1.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 11902,
                    'product_name'                   => 'チョコレートデコレーション　4号',
                    'product_price'                  => 2592,
                    'product_size'                   => '2',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】チョコレートクリームの上にフルーツものせて。

        ※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD2.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 12102,
                    'product_name'                   => 'チョコレートデコレーション　5号',
                    'product_price'                  => 3132,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】チョコレートクリームの上にフルーツものせて。

        ※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD2.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 12270,
                    'product_name'                   => 'チョコレートデコレーション　6号',
                    'product_price'                  => 3966,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】チョコレートクリームの上にフルーツものせて。

        ※使用するフルーツは季節によって異なることがございます。',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material/F10143528000001_BD2.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 12405,
                    'product_name'                   => '苺のデコレーションケーキ　4号',
                    'product_price'                  => 2916,
                    'product_size'                   => '2',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】旬の苺をふんだんに使ったケーキ。甘さ控えめの軽い口当たりのクリームにぴったりです',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10143528000001_BD4.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 12543,
                    'product_name'                   => '苺のデコレーションケーキ　5号',
                    'product_price'                  => 3672,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】旬の苺をふんだんに使ったケーキ。甘さ控えめの軽い口当たりのクリームにぴったりです',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10143528000001_BD4.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 12671,
                    'product_name'                   => '苺のデコレーションケーキ　6号',
                    'product_price'                  => 4860,
                    'product_size'                   => '4',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】旬の苺をふんだんに使ったケーキ。甘さ控えめの軽い口当たりのクリームにぴったりです',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10143528000001_BD4.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42017,
                    'facility_name'                  => 'FOUR SEASONS CAFE（フォーシーズンズカフェ）',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10143528000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '江戸川区',
                    'district'                       => '西葛西6-5-12',
                    'building_name'                  => '',
                    'addr_latitude'                  => '35.663878',
                    'addr_longitude'                 => '139.857331',
                    'display_tel_no'                 => '03-3689-1173',
                    'station1'                       => '西葛西駅',
                    'exit_station1'                  => '南口出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '2',
                ),
                array(
                    'product_id'                     => 1048,
                    'product_name'                   => '生クリームデコレーション 4号',
                    'product_price'                  => 2484,
                    'product_size'                   => '2',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】ふわふわスポンジと軽くてやわらかい生クリームの中には、スライスした苺が2段サンドに。季節のフルーツで可愛く飾りました。(卵・小麦粉・乳)',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10153806000001_BD01_3.jpg',
                    'product_image2'                 => 'http://s7790605.xaas.jpimages/material/F10153806000001_BD01_2.jpg',
                    'product_image3'                 => 'http://s7790605.xaas.jpimages/material/F10153806000001_BD01_1.jpg',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42562,
                    'facility_name'                  => 'ケーキファクトリースマイル',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10153806000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '西東京市',
                    'district'                       => '田無町4-17-18',
                    'building_name'                  => 'ドミール田無',
                    'addr_latitude'                  => '35.729668',
                    'addr_longitude'                 => '139.535656',
                    'display_tel_no'                 => '042-497-6120',
                    'station1'                       => '田無駅',
                    'exit_station1'                  => '北出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '6',
                ),
                array(
                    'product_id'                     => 2288,
                    'product_name'                   => '生クリームデコレーション 5号',
                    'product_price'                  => 2970,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】ふわふわスポンジと軽くてやわらかい生クリームの中には、スライスした苺が2段サンドに。季節のフルーツで可愛く飾りました。(卵・小麦粉・乳)',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10153806000001_BD01_3.jpg',
                    'product_image2'                 => 'http://s7790605.xaas.jpimages/material/F10153806000001_BD01_2.jpg',
                    'product_image3'                 => 'http://s7790605.xaas.jpimages/material/F10153806000001_BD01_1.jpg',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42562,
                    'facility_name'                  => 'ケーキファクトリースマイル',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10153806000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '西東京市',
                    'district'                       => '田無町4-17-18',
                    'building_name'                  => 'ドミール田無',
                    'addr_latitude'                  => '35.729668',
                    'addr_longitude'                 => '139.535656',
                    'display_tel_no'                 => '042-497-6120',
                    'station1'                       => '田無駅',
                    'exit_station1'                  => '北出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '6',
                ),
                array(
                    'product_id'                     => 3516,
                    'product_name'                   => 'チョコクリームデコレーション　4号',
                    'product_price'                  => 2484,
                    'product_size'                   => '2',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】生デコレーションをチョコクリームで作りました。ふわふわスポンジもチョコスポンジに変身！(卵・小麦粉・乳)',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10153806000001_BD02.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42562,
                    'facility_name'                  => 'ケーキファクトリースマイル',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10153806000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '西東京市',
                    'district'                       => '田無町4-17-18',
                    'building_name'                  => 'ドミール田無',
                    'addr_latitude'                  => '35.729668',
                    'addr_longitude'                 => '139.535656',
                    'display_tel_no'                 => '042-497-6120',
                    'station1'                       => '田無駅',
                    'exit_station1'                  => '北出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '6',
                ),
                array(
                    'product_id'                     => 4736,
                    'product_name'                   => 'チョコクリームデコレーション　5号',
                    'product_price'                  => 2970,
                    'product_size'                   => '3',
                    'reservation_flg'                => '1',
                    'product_description1'           => '【WEB予約で500円OFF】ふわふわスポンジと軽くてやわらかい生クリームの中には、スライスした苺が2段サンドに。季節のフルーツで可愛く飾りました。(卵・小麦粉・乳)',
                    'product_image1'                 => 'http://s7790605.xaas.jp/images/material//F10153806000001_BD02.jpg',
                    'product_image2'                 => '',
                    'product_image3'                 => '',
                    'product_image4'                 => '',
                    'product_image5'                 => '',
                    'product_image6'                 => '',
                    'product_image7'                 => '',
                    'product_image8'                 => '',
                    'product_image9'                 => '',
                    'product_image10'                => '',
                    'product_comment_num'            => 8,
                    'product_comment_evaluate_total' => 3.5,
                    'shop_id'                        => 42562,
                    'facility_name'                  => 'ケーキファクトリースマイル',
                    'main_image_s'                   => 'http://s7790605.xaas.jp/images/material/F10153806000001_main.jpg',
                    'prov_name'                      => '東京都',
                    'city'                           => '西東京市',
                    'district'                       => '田無町4-17-18',
                    'building_name'                  => 'ドミール田無',
                    'addr_latitude'                  => '35.729668',
                    'addr_longitude'                 => '139.535656',
                    'display_tel_no'                 => '042-497-6120',
                    'station1'                       => '田無駅',
                    'exit_station1'                  => '北出口',
                    'means1'                         => '徒歩',
                    'time_required1'                 => '6',
                ),
            )
        );

        return response()->json($json);
    }

    public function detail($id){
          $json = array(
               'status'    => 0,
               'items'     => array(
                    array(
                         'product_id'           => 1120,
                         'product_name'         => '生クリーム デコレーション　5号',
                         'product_price'        => 2370,
                         'product_size'         => '3',
                         'reservation_flg'      => '1',
                         'product_description1' => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                         'product_image1'       => 'http://s7790605.xaas.jp/images/material/F10154712000001_BD1.jpg',
                         'product_image2'       => '',
                         'product_image3'       => '',
                         'product_image4'       => '',
                         'product_image5'       => '',
                         'product_image6'       => '',
                         'product_image7'       => '',
                         'product_image8'       => '',
                         'product_image9'       => '',
                         'product_image10'      => '',
                         'catch_copy'           => '【WEB予約で500円OFF】お誕生日やお祝いに定番のいちごと生クリームのデコレーションケーキ。創業から変わらぬ味で、地元の方に親しまれています。ご希望のメッセージをお入れいたします。',
                         'product_description2' => '',
                         'product_description3' => '',
                         'reserve_site_url'     => '',
                         'any_item_1'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_2'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_3'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_4'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_5'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_6'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_7'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_8'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_9'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'any_item_10'           => array(
                              'pulldown' => array(
                                   'option_name'  => '',
                                   'option_item'  => '',
                                   'option_price' => '',
                                   'option_note'  => '',
                              ),
                              'textbox' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                              'textarea' => array(
                                   'option_name'    => '',
                                   'option_example' => '',
                                   'option_note'    => '',
                              ),
                         ),
                         'preferred_days'                 => '[月曜日,火曜日,水曜日,木曜日,金曜日,土曜日,日曜日,祝曜日]',
                         'preferred_max_stock_4monday'    => 100,
                         'preferred_max_stock_4tuesday'   => 100,
                         'preferred_max_stock_4wednesday' => 100,
                         'preferred_max_stock_4thursday'  => 100,
                         'preferred_max_stock_4friday'    => 100,
                         'preferred_max_stock_4saturday'  => 100,
                         'preferred_max_stock_4sunday'    => 100,
                         'preferred_max_stock_4holiday'   => 100,

                         'category_region_1'              => array(
                              'region_category_id' => 783,
                              'category_name' => '東京(市区郡から探す)',
                         ),
                         'category_region_2'              => array(
                              'region_category_id' => 39,
                              'category_name' => '世田谷区',
                         ),
                         'category_region_3'              => array(
                              'region_category_id' => null,
                              'category_name' => '',
                         ),
                         'category_products'           => array(
                              'category_product_1' => array(
                                   'product_category_id'  => 1,
                                   'category_name'  => '誕生日ケーキ・ホールケーキ',
                              ),
                              'category_product_2' => array(
                                   'product_category_id'  => 14,
                                   'category_name'  => 'ショートケーキ',
                              ),
                              'category_product_3' => array(
                                   'product_category_id'  => 195,
                                   'category_name'  => '生クリーム',
                              ),
                         ),
                         'comment_num'                 => 50,
                         'comment_evaluate_total'      => 3,
                         'image_post_flg'              => 0,
                         'product_cancellation_policy' => 'キャンセルポリシー',
                         'today_sales_flg'             => 0,
                         'today_reservation_time'      => 12,
                         'before_reservation_day'      => 3,
                         'before_reservation_time'     => 12,
                         'shop_discount'               => 100,
                         'portal_discount'             => 200,
                    ),
               ),
          );
          return response()->json($json);

          
    }
}