<?php

namespace App\Http\Controllers\Api;

class ShopController extends ApiController
{
	public function detail(){
		$json = array(
			'status'    => 0,
			'items'     => array(
				array(
					'contract_tp'          => '2',
					'display_flg'          => '1',
					'display_ranking'      => '3',
					'pdb_customer_no'      => '12345678',
					'pdb_contract_no'      => '123456789012345',
					'chain_name'           => '',
					'co_name'              => '',
					'facility_name'        => '和洋菓子 好月堂',
					'facility_name_kana'   => 'ワヨウガシ コウゲツドウ',
					'delegate_name'        => '代表者名',
					'post_code'            => '156-0056',
					'prov_name'            => '東京都',
					'city'                 => '世田谷区',
					'district'             => '八幡山3-35-24',
					'building_name'        => '1F',
					'addr_latitude'        => 35.669068,
					'addr_longitude'       => 139.615774,
					'online_map_address'   => '東京都世田谷区八幡山3-35-241F',
					'tel_no'               => '03-3303-5316',
					'fax_no'               => '03-9999-9999',
					'display_tel_no'       => '03-3303-5316',
					'call_tracking_no'     => 'tracking_no',
					'site_url_pc'          => 'http://www.wagashi.or.jp/tokyo_link/shop/2232.htm',
					'site_url_mobile'      => 'http://www.wagashi.or.jp/tokyo_link/shop/2232.htm',
					'related_links_title1' => '',
					'related_links_url1'   => '',
					'related_links_title2' => '',
					'related_links_url2'   => '',
					'related_links_title3' => '',
					'related_links_url3'   => '',
					'related_links_title4' => '',
					'related_links_url4'   => '',
					'open_date'            => '',
					'station1'             => '八幡山駅',
					'exit_station1'        => '',
					'means1'               => '徒歩',
					'time_required1'       => '2',
					'station2'             => '',
					'exit_station2'        => '',
					'means2'               => '',
					'time_required2'       => '',
					'station3'             => '',
					'exit_station3'        => '',
					'means3'               => '',
					'time_required3'       => '',
					'station4'             => '',
					'exit_station4'        => '',
					'means4'               => '',
					'time_required4'       => '',
					'station5'             => '',
					'exit_station5'        => '',
					'means5'               => '',
					'time_required5'       => '',
					'access_detail'        => '京王線　八幡山駅 徒歩 2分',
					'working_times'        => array(
						'working_times_1' => array(
							'start'   => '09:30',
							'end'     => '20:00',
							'mon'     => '0',
							'tue'     => '1',
							'wed'     => '0',
							'thu'     => '1',
							'fri'     => '1',
							'sat'     => '0',
							'sun'     => '0',
							'holiday' => '1',
						),
						'working_times_2' => array(
							'start'   => '09:30',
							'end'     => '20:00',
							'mon'     => '0',
							'tue'     => '1',
							'wed'     => '0',
							'thu'     => '1',
							'fri'     => '1',
							'sat'     => '0',
							'sun'     => '1',
							'holiday' => '1',
						),
						'working_times_3' => array(
							'start'   => '09:30',
							'end'     => '20:00',
							'mon'     => '0',
							'tue'     => '1',
							'wed'     => '0',
							'thu'     => '1',
							'fri'     => '1',
							'sat'     => '1',
							'sun'     => '1',
							'holiday' => '1',
						),
						'working_times_4' => array(
							'start'   => '09:30',
							'end'     => '20:00',
							'mon'     => '1',
							'tue'     => '1',
							'wed'     => '0',
							'thu'     => '0',
							'fri'     => '1',
							'sat'     => '1',
							'sun'     => '0',
							'holiday' => '1',
						),
					),
					'calendar_comment' => '',
					'shop_news'        => array(
						'shop_news_1' => array(
							'news_title'     => '',
							'news_title_url' => '',
							'news_text'      => '',
							'news_img'       => '',
							'display_flg'    => '',
						),
						'shop_news_2' => array(
							'news_title'     => '',
							'news_title_url' => '',
							'news_text'      => '',
							'news_img'       => '',
							'display_flg'    => '',
						),
						'shop_news_3' => array(
							'news_title'     => '',
							'news_title_url' => '',
							'news_text'      => '',
							'news_img'       => '',
							'display_flg'    => '',
						),
						'shop_news_4' => array(
							'news_title'     => '',
							'news_title_url' => '',
							'news_text'      => '',
							'news_img'       => '',
							'display_flg'    => '',
						),
					),
					'introducer'               => '',
					'introduce_comment'        => '',
					'page_title'               => '和洋菓子 好月堂 - 八幡山（東京都 世田谷区） ',
					'meta_keyword'             => '和洋菓子 好月堂,東京都世田谷区,八幡山',
					'search_keyword'           => '',
					'meta_description'         => 'おすすめスイーツ情報だけでなく、営業時間、店舗情報なども充実!! 昭和41年から八幡山に店を構える、レトロな和洋菓子店',
					'catch_copy'               => '昭和41年から八幡山に店を構える、レトロな和洋菓子店',
					'list_comment'             => '和洋菓子 好月堂は大正時代に創業した根津・好月堂から独立し、昭和41年に八幡山にお店を構えました。昔ながらの店構えで、慶弔菓子、四季を彩るお茶菓子や生菓子、進物用和洋菓子のほか、バースデーケーキ、各種ケーキなど、真心を込めて風味豊かな手造り菓子を取り揃えています。また、お誕生日やお祝い用のデコレーションケーキの予約も承っています。地方発送にも対応しています。',
					'introdyctory_essay'       => '',
					'main_image'               => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
					'main_image_s'             => 'http://s7790605.xaas.jp/images/material/F10154712000001_main.jpg',
					'subhead1'                 => '八幡山駅から徒歩2分、昭和41年創業のレトロなお菓子屋さん',
					'subhead2'                 => '和菓子から洋菓子まで様々なお菓子が並ぶショーケース',
					'subhead3'                 => '開業当時から不動の人気商品「ママン」',
					'subhead4'                 => '',
					'subhead5'                 => '',
					'subhead6'                 => '',
					'sub_image1'               => 'http://s7790605.xaas.jp/images/material/F10154712000001_sub01.jpg',
					'sub_image2'               => 'http://s7790605.xaas.jp/images/material/F10154712000001_sub02.jpg',
					'sub_image3'               => 'http://s7790605.xaas.jp/images/material/F10154712000001_sub03.jpg',
					'sub_image4'               => 'http://s7790605.xaas.jp/images/material/F10154712000001_sub01.jpg',
					'sub_image5'               => '',
					'sub_image6'               => '',
					'explanation1'             => '和洋菓子 好月堂は、京王線 八幡山駅から徒歩2分のところにございます。
		緑・黄・赤の3色のオーニングテント、昭和41年創業の老舗らしいレトロな外観が目印です。',
					'explanation2'             => '慶弔菓子、四季を彩るお茶菓子や生菓子、進物用菓子のほか、バースデーケーキ、各種ケーキなど
		和菓子から洋菓子まで種類豊富な品揃えです。
		帰省など、お出かけの時のお土産菓子にいかがでしょうか。
		またお祝い行事のお赤飯、お餅、お饅頭や仏事用の御菓子等のご相談、ご注文も承っています。
		地方発送も対応しています。',
					'explanation3'             => 'ふんわり焼き上げた素朴な味のブッセに、口どけよいチーズバタークリームとさわやかな杏ジャムをサンドしました。
		口にすれば遠い昔の記憶が蘇ってきそうな懐かしいお味です。',
					'explanation4'             => 'ふんわり焼き上げた素朴な味のブッセに、口どけよいチーズバタークリームとさわやかな杏ジャムをサンドしました。
		口にすれば遠い昔の記憶が蘇ってきそうな懐かしいお味です。',
					'explanation5'             => '',
					'explanation6'             => '',
					'reservations_notes'       => '',
					'reservations_fax_no'      => '',
					'reservations_mailaddress' => '',
					'coupon_tab'               => '',
					'coupon_informations'      => array(
						'coupon_informations_1' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_2' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_3' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_4' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_5' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_6' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_7' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_8' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_9' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_10' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_11' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_12' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_13' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_14' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_15' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
						'coupon_informations_16' => array(
							'coupon_name'                  => '',
							'coupon_use_cond'              => '',
							'coupon_presentation_cond'     => '',
							'coupon_note'                  => '',
							'coupon_expiration_date_txt'   => '',
							'coupon_carrying_period_start' => '',
							'coupon_carrying_period_end'   => '',
						),
					),
					'youtube_video_id'    => '',
					'youtube_playlist_id' => '',
					'shop_photo_url'      => '',
					'compatible_service'  => '[クーポン有り, Web予約有り, テイクアウト, 手土産, 贈答用ギフト, バースデーケーキ, バースデーケーキ（予約）, 引き出物対応, ギフトラッピング]',
					'handled_product'     => '[ショートケーキ,チョコレートケーキ,チーズケーキ,ロールケーキ,シフォンケーキ,ティラミス]',
					'category_1'              => array(
						'region_category_id' => 783,
						'category_name' => '東京(市区郡から探す)',
					),
					'category_2'              => array(
						'category_id' => 39,
						'category_name' => '世田谷区',
					),
					'category_3'              => array(
						'category_id' => null,
						'category_name' => '',
					),
					'comment_num'             => '30',
					'comment_evaluate_total'  => '2.6',
					'product_genres' => array(
						'genre_id'   => '',
						'genre_name' => '',
					),
					'shop_cancellation_policy' => 'キャンセルポリシー',
				),
			),
		);
		return response()->json($json);
	}


}