<ul class="search-cities">
    <li><a href="/hokkaido" data-region-id="2">北海道</a></li>
    <li><a href="/aomori" data-region-id="7">青森県</a></li>
    <li><a href="/iwate" data-region-id="10">岩手県</a></li>
    <li><a href="/miyagi" data-region-id="13">宮城県</a></li>
    <li><a href="/akita" data-region-id="16">秋田県</a></li>
    <li><a href="/fukushima" data-region-id="20">福島県</a></li>
    <li><a href="/yamagata" data-region-id="19">山形県</a></li>
    <li><a href="/tokyo-searchfromcitycounty" data-region-id="783">東京都</a></li>
    <li><a href="/kanagawa" data-region-id="50">神奈川県</a></li>
    <li><a href="/chiba" data-region-id="60">千葉県</a></li>
    <li><a href="/saitama" data-region-id="56">埼玉県</a></li>
    <li><a href="/gunma" data-region-id="69">群馬県</a></li>
    <li><a href="/ibaraki" data-region-id="68">茨城県</a></li>
    <li><a href="/tochigi" data-region-id="65">栃木県</a></li>
    <li><a href="/yamanashi" data-region-id="91">山梨県</a></li>
    <li><a href="/shizuoka" data-region-id="83">静岡県</a></li>
    <li><a href="/aichi" data-region-id="74">愛知県</a></li>
    <li><a href="/mie" data-region-id="87">三重県</a></li>
    <li><a href="/gifu" data-region-id="80">岐阜県</a></li>
    <li><a href="/niigata" data-region-id="88">新潟県</a></li>
    <li><a href="/nagano" data-region-id="92">長野県</a></li>
    <li><a href="/ishikawa" data-region-id="95">石川県</a></li>
    <li><a href="/toyama" data-region-id="98">富山県</a></li>
    <li><a href="/fukui" data-region-id="101">福井県</a></li>
    <li><a href="/osaka" data-region-id="103">大阪府</a></li>
    <li><a href="/hyogo" data-region-id="111">兵庫県</a></li>
    <li><a href="/kyoto" data-region-id="117">京都府</a></li>
    <li><a href="/shiga" data-region-id="120">滋賀県</a></li>
    <li><a href="/wakayama" data-region-id="126">和歌山県</a></li>
    <li><a href="/nara" data-region-id="123">奈良県</a></li>
    <li><a href="/okayama" data-region-id="130">岡山県</a></li>
    <li><a href="/hiroshima" data-region-id="134">広島県</a></li>
    <li><a href="/tottori" data-region-id="138">鳥取県</a></li>
    <li><a href="/shimane" data-region-id="139">島根県</a></li>
    <li><a href="/yamaguchi" data-region-id="140">山口県</a></li>
    <li><a href="/kagawa" data-region-id="143">香川県</a></li>
    <li><a href="/tokushima" data-region-id="146">徳島県</a></li>
    <li><a href="/ehime" data-region-id="147">愛媛県</a></li>
    <li><a href="/kochi" data-region-id="150">高知県</a></li>
    <li><a href="/fukuoka" data-region-id="154">福岡県</a></li>
    <li><a href="/saga" data-region-id="159">佐賀県</a></li>
    <li><a href="/nagasaki" data-region-id="160">長崎県</a></li>
    <li><a href="/kumamoto" data-region-id="163">熊本県</a></li>
    <li><a href="/oita" data-region-id="166">大分県</a></li>
    <li><a href="/miyazaki" data-region-id="169">宮崎県</a></li>
    <li><a href="/kagoshima" data-region-id="172">鹿児島県</a></li>
    <li><a href="/okinawa" data-region-id="175">沖縄県</a></li>
</ul>
